[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

Radarin is a project for the course of Software Architecture of the University of Oviedo. This version will be depeloped by the members of the team EN3B who are:

- Juan Buenaga Díaz
- Miguel Ligero Arbesú
- Carmen Rendueles Martínez
- Álvaro Requejo Cembellín
- Juan Rodríguez de la Fuente
- Marcos Tobias Muñiz

Radarin is an application to allow users to find friends that are close to his/her position by receiving a notification when one of them is close enough.
This will be done with a mobile application that will store the location of the users but following the SOLID approach to ensure that users privacy is respected.
A web application will also be developed to allow the user to see and manage his/her for locations.  

=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

The application will run basically on the server, all of the users information will be stored in users pod. Only locations and timestamps that will be stored on the server but not linked to any personal information. 
To get information of other users the app will query their corresponding pods. All of this requirements are compatible with the SOLID project as no user information is stored in a centralized way.

In the web application users will be able to manage and visualize its locations. And it will also include some user management and server status monitoring options.

The mobile application will basically send locations to the server and receive notifications from friends close to the location of the user.

The possibility of uploading multimedia content related to locations will also be offered.

==== Technical requirements

For the deployment of the system, docker containers and a cloud service like heroku will be used.

It’s correct behaviour will be monitored through unit tests, acceptance tests and load tests which will be done and runned in a continuous integration server.


=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
[options="header",cols="1,2,2"]
|===
|Priority|Quality|Motivation
| 1 | Usability | The application should have a good aesthetic and be easy to use for all kinds of users.
| 2 | Privacy | The application must take only the strictly necessary data from the users and use it only for the necessary purpose. The data should not be centralized.
| 3 | Security | The system must be secure and data must not be given to third parties.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Students | Juan Buenaga Díaz, Miguel Ligero Arbesú, Carmen Rendueles Martínez, Álvaro Requejo Cembellín, Juan Rodríguez de la Fuente and Marcos Tobias Muñiz | Principal developers of the application. They will develop the whole application and as a consequence they Will improve their coding skills and their teamwork capacity.
| Teachers | José Emilio Labra Gallo| They will supervise students work and make sure they are going in the correct direction and help them with some things if necessary
|===
