[[section-introduction-and-goals]]
== Introduction and Goals

Radarin is a project for the course of Software Architecture of the University of Oviedo. This version will be depeloped by the members of the team EN3B who are:

- Juan Buenaga Díaz
- Miguel Ligero Arbesú
- Carmen Rendueles Martínez
- Álvaro Requejo Cembellín
- Juan Rodríguez de la Fuente
- Marcos Tobias Muñiz

Radarin is an application to allow users to find friends that are close to his/her position by receiving a notification when one of them is close enough.
This will be done with a mobile application that will store the location of the users but following the SOLID approach to ensure that users privacy is respected.
A web application will also be developed to allow the user to see and manage his/her for locations.  

=== Requirements Overview

The application will run basically on the server, all of the users information will be stored in users pod. Only locations and timestamps that will be stored on the server but not linked to any personal information. 
To get information of other users the app will query their corresponding pods. All of this requirements are compatible with the SOLID project as no user information is stored in a centralized way.

In the web application users will be able to manage and visualize its locations. And it will also include some user management and server status monitoring options.

The mobile application will basically send locations to the server and receive notifications from friends close to the location of the user.

The possibility of uploading multimedia content related to locations will also be offered.

==== Technical requirements

For the deployment of the system, docker containers and a cloud service like heroku will be used.

It’s correct behaviour will be monitored through unit tests, acceptance tests and load tests which will be done and runned in a continuous integration server.


=== Quality Goals

 [options="header",cols="1,2,2"]
|===
|Priority|Quality|Motivation
| 1 | Usability | The application should have a good aesthetic and be easy to use for all kinds of users.
| 2 | Privacy | The application must take only the strictly necessary data from the users and use it only for the necessary purpose. The data should not be centralized.
| 3 | Security | The system must be secure and data must not be given to third parties.
|===

=== Stakeholders

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Students | Juan Buenaga Díaz, Miguel Ligero Arbesú, Carmen Rendueles Martínez, Álvaro Requejo Cembellín, Juan Rodríguez de la Fuente and Marcos Tobias Muñiz | Principal developers of the application. They will develop the whole application and as a consequence they Will improve their coding skills and their teamwork capacity.
| Teachers | José Emilio Labra Gallo| They will supervise students work and make sure they are going in the correct direction and help them with some things if necessary.
| Users || Users will be the ones using the application so they must find it usable and practical.
|Other students|| Other students may help the team developers in concrete moments by giving advise, or trying the app or helping in any other way.
|Server admin || This would be the person in charge of managing and controlling the server status and fixing the problems that may arise related to it.
|===
