[[section-architecture-constraints]]
== Architecture Constraints

We will divide them in two main parts: technical constraints and business constraints.

=== Technical Constraints

Ones related to fixed technical design desicions that cannot be changed.

[%header, cols=2]
|===
|Constraint
|Explanation

|JavaScript
|JavaScript will be used both in the frontend and backend of the project, facilitating the process
of understanding the code and allowing us to work in different parts of the application without the 
need of distributing tasks based on programming language expertise

|Windows, Linux, iOS and Android
|The application have two parts, one web application that will be supported by every browser,
and a mobile app supported for both Android and iOS

|React
|A library based on JavaScript that we will use for the frontend of the application, both in the
web and in mobile versions, using react native in the latter

|Node
|A runtime environment for JavaScript that will help us build the backend of the application. Its oftently used with react as they are both based on JavaScript

|Git
|GitHub is a framework for creating a Version Control System

|===

=== Business Constraints

Ones related on unchangeable business decisions that restrict the software architecture design.

[%header, cols=2]
|===
|Constraint
|Explanation

|Schedule
|We have to finish the application by the end of the semester

|Bugdet
|As we are students and this proyect is part of the subjet, we have no budget, which implies that
we won't be able to use any paid software or tools

|Team composition
|The development team consists in 6 people

|===

[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
