[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Solid for backend authentication
We want to keep things simple so we are not going to create our own user/password accounts so, in order to provide a mechanism to authenticate our users in the backend (we don't want anyone to send a fake location along another user's ID), we are going to send the JWT token that we get from the Identity Provider to our RestAPI. Our api will then ask for the public key at the Identity Provider's */jwks* endpoint, store it in cache and verify the authenticated messages that the user sends from the App.

=== Store current user locations

This is an example about how we handle authenticated requests in the backend:

[plantuml,"Current user location diagram",png]
----
actor Bob
participant PhoneApp
participant RestAPI
participant IDProvider
database MongoDb as "Database"
Bob -> PhoneApp: Press "Log-In"
PhoneApp --> Bob: Asks user for its provider
Bob -> IDProvider: Logs into his provider
IDProvider --> PhoneApp: Provides Token
Bob -> PhoneApp: Bob clicks "Store location"
PhoneApp  -> RestAPI: Sends location with token
RestAPI -> IDProvider: Asks for public key to verify token
IDProvider --> RestAPI: Sends public key
RestAPI -> MongoDb: Stores location
MongoDb --> RestAPI: Notify success
RestAPI --> PhoneApp: Notify success
PhoneApp --> Bob: Shows a "done!" toast
----
=== Check for users nearby
Here we have omitted authentication steps as they are already stated in previous diagrams. The following conditions must be met before this diagram:
 * The user is logged-in.
 * The user has given the POD permission for us to look at their friends.

[plantuml,"Check for other users diagram",png]
----
participant PhoneApp
participant RestAPI
database Pod as "Bob's Pod"
database MongoDB as "Database"
PhoneApp -> RestAPI: Check if there's a friend nearby
RestAPI -> Pod: Asks for friend list
Pod --> RestAPI: Sends friend list
RestAPI -> MongoDB: Asks for friend location
MongoDB --> RestAPI: Sends friend location
RestAPI --> PhoneApp: Send nearby users
----

