[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

[plantuml, "Deployment diagram",png]
----
node <<device>>\nClientPC as n1{
node <<execution\tenvironment>>\n:WebBrowser{
rectangle :Website{
}
}
}

node <<device>>\n:WebServer as n2{
node <<execution\tenvironment>>\n:GithubPages{
}
}

rectangle :Radarin as r1{
}

node <<device>>\nPodProvider(Solid) as n3{
node <<execution\tenvironment>>\n:PodServer{
rectangle :PodInstance{
}
}
}

cloud OpenStreetMapAPI as c1{
}

n1 --> n2 : //http//
n2  <..  r1  : //deploys//
r1 --> n3 : //http//
c1 <- r1 : //uses//
----

Motivation::

The motivation of this deployment structure is the correct understanding of how nodes and components of the project behave and are related in runtime.

Quality and/or Performance Features::

The performance mainly depends on the network connection from the user and the servers on which the application runs. We cannot control those two things, but we can improve as much as possible the quality of the application by writing the cleanest possible code.

Mapping of Building Blocks to Infrastructure::

[%header, cols=2]
|===
|Element
|Description

|ClientPC
|Device of the user, it must have a connection to the Internet

|:WebServer
|Server used by the browser. Every browser should be valid.

|:PodProvider
|Solid PODs are provided by Solid Community or Inrupt servers.

|:Radarin
|Our app hosted in GitHub pages.

|OpenStreetMapAPI
|Free maps API that will be used by Radarin. More APIs could be used in the future.

|===


=== Infrastructure Level 2

[role="arc42help"]
****
Here you can include the internal structure of (some) infrastructure elements from level 1.

Please copy the structure from level 1 for each selected element.
****

==== _<Infrastructure Element 1>_

_<diagram + explanation>_

==== _<Infrastructure Element 2>_

_<diagram + explanation>_

...

==== _<Infrastructure Element n>_

_<diagram + explanation>_
