[[section-quality-scenarios]]
== Quality Requirements
In this section, the point 1.2 is extended, describing the quality requirements of our application.

[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.
****

=== Quality Tree
[plantuml, "Quality tree",png]
----
left to right direction
(Quality) as (Q)
(Usability) as (U)
(Privacy) as (Pr)
(Security) as (S)
(Reliability) as (R)
(Maintainability) as (M)
(Portability) as (P)
(Compatibility) as (C)
Q --> U
Q --> Pr
Q --> S
Q --> R
Q --> M
Q --> P
Q --> C
----
[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.
****

=== Quality Scenarios

[%header, cols=3]
|===
|Quality requirement
|Quality scenario
|Priority

|Usability
|Users have to be able to navigate through the application in an intuitive way
|High

|Privacy
|Private data from the users have to be protected. The application only takes essential data from the user, and these data are not centralized.
|High

|Security
|The application have to be highly secure for the users, data should never be given to any thrid part, and application must prevent user's data leak
|High

|Reliability
|All the errors of the application have to be handled by the application itself, there should not be system crashes.
|Medium-High

|Maintainability
|The application should be written in a way that code can be reused and modified in a simple way, bugs can be easily found and fixed, and the program should be easy to test.
|Medium

|Portability
|The application should be adapted to the device where it is deployed, from computers to mobile phones or tablets.
|Low-Medium

|Compatibility
|The application should be capable of operat satisfactorily together with another system on the same computer or different computers.
|Low-Medium

|===

[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
