[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

[%header, cols=2]
|===
|Risk 
|Measures we are taking

|Having a huge payload
|This may be mitigated with a 

|===

[%header, cols=2]
|===
|Technical debts

|

|Code debts
|Description

|The team is not familiar with Solid
|Practising and asking the teacher for advise and personal research.

|Making the project with React
|Being JS a language recently learned and the library used for the first time, several guides and manuals will be used

|

|Design debts
|Description

|

|Test debts
|Description

|===

